[package]
name = "final_project"
version = "0.1.0"
authors = ["Jiya Patidar <jiya2@illinois.edu> Michael Reeve <mreeve2@illinois.edu> Shanav Bagga <svbagga2@illinois.edu> Howard Ding <howardd2@illinois.edu>"]
edition = "2021"

[dependencies]
rust-bert = "0.10.0"
tch = "0.4.1"
tokenizers = "0.11"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
